#!/usr/bin/python3
'''This file creates a class that inherits from the built-in list'''

class MyList(list):
    '''This class inherits the built-in list class'''

    def print_sorted(self):
        '''Prints the list in ascending order'''
        sorted_list = sorted(self)
        print("{}".format(sorted_list))

